### ISSUE TITLE
some libraries have cyclical dependencies

### ISSUE THREAD

**Issue by matthewmueller** [dominicbarnes/node-graph-toposort#1]
Unfortunately I don't think these lines are going to work: 

https://github.com/dominicbarnes/node-graph-toposort/blob/master/index.js#L31-L33

Here's an example library that has a cycle:
- https://github.com/ProseMirror/prosemirror/blob/master/src/edit/main.js#L19
- https://github.com/ProseMirror/prosemirror/blob/master/src/edit/draw.js#L5

I'm not exactly sure what the right solution is here, probably just quit traversing that cycle, but I think this will need to be addressed since it breaks mako builds upstream.

**Comment by dominicbarnes** [comment]
v0.1 includes a fix for this, so we'll have to wait and see if it turns out to work well in practice.
